Minor changes in output.
When not in verbose mode, outputs messages more standard, eg.

    error: gnatprove: no such file or directory

Change-Id: Iff589831300ae437ab2f60799c26d0bb6da9f1dc